[tool.poetry]
name = 'michbday'
version = '1.0.0'
description = 'Wishing mich a happy bday'
authors = 'palyfight chrisbama92@gmail.com'

[tool.poetry.dependencies]
python = '^3.9'
art = '~5.1'

[build-system]
requires = ['poetry-core~=1.0']
build-backend = 'poetry.core.masonry.api'